# Generated by Django 5.1.4 on 2025-01-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="title",
            name="date_created",
        ),
        migrations.AlterField(
            model_name="title",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
